// Generated by nitro

// App Config
import type { Defu } from 'defu'

import type { default as appConfig0 } from "/Users/aziza/Desktop/Insa/INSA-LYON-4A/PLD-SMART/Arca/nuxt-ui-pro-dashboard/app.config";
import type { default as appConfig1 } from "/Users/aziza/Desktop/Insa/INSA-LYON-4A/PLD-SMART/Arca/nuxt-ui-pro-dashboard/node_modules/.pnpm/@nuxt+ui-pro@1.0.2_axios@1.6.8_nuxt@3.10.3_@parcel+watcher@2.4.0_@types+node@20.11.19_encodin_iatrsbsja24ozpieearqoymouy/node_modules/@nuxt/ui-pro/app.config";

type UserAppConfig = Defu<{}, [typeof appConfig0, typeof appConfig1]>

declare module 'nitropack' {
  interface AppConfig extends UserAppConfig {}
}
    
export {}