// Generated by Nuxt'
import type { Plugin } from '#app'

type Decorate<T extends Record<string, any>> = { [K in keyof T as K extends string ? `$${K}` : never]: T[K] }

type IsAny<T> = 0 extends 1 & T ? true : false
type InjectionType<A extends Plugin> = IsAny<A> extends true ? unknown : A extends Plugin<infer T> ? Decorate<T> : unknown

type NuxtAppInjections = 
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.10.3_@parcel+watcher@2.4.0_@types+node@20.11.19_encoding@0.1.13_eslint@8.57.0_optionat_s7d46f3i2xvimlar2kzdzkszge/node_modules/nuxt/dist/app/plugins/check-outdated-build.client").default> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.10.3_@parcel+watcher@2.4.0_@types+node@20.11.19_encoding@0.1.13_eslint@8.57.0_optionat_s7d46f3i2xvimlar2kzdzkszge/node_modules/nuxt/dist/app/plugins/revive-payload.server").default> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.10.3_@parcel+watcher@2.4.0_@types+node@20.11.19_encoding@0.1.13_eslint@8.57.0_optionat_s7d46f3i2xvimlar2kzdzkszge/node_modules/nuxt/dist/app/plugins/revive-payload.client").default> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.10.3_@parcel+watcher@2.4.0_@types+node@20.11.19_encoding@0.1.13_eslint@8.57.0_optionat_s7d46f3i2xvimlar2kzdzkszge/node_modules/nuxt/dist/head/runtime/plugins/unhead").default> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.10.3_@parcel+watcher@2.4.0_@types+node@20.11.19_encoding@0.1.13_eslint@8.57.0_optionat_s7d46f3i2xvimlar2kzdzkszge/node_modules/nuxt/dist/pages/runtime/plugins/router").default> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.10.3_@parcel+watcher@2.4.0_@types+node@20.11.19_encoding@0.1.13_eslint@8.57.0_optionat_s7d46f3i2xvimlar2kzdzkszge/node_modules/nuxt/dist/pages/runtime/plugins/prefetch.client").default> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.10.3_@parcel+watcher@2.4.0_@types+node@20.11.19_encoding@0.1.13_eslint@8.57.0_optionat_s7d46f3i2xvimlar2kzdzkszge/node_modules/nuxt/dist/pages/runtime/plugins/check-if-page-unused").default> &
  InjectionType<typeof import("../../node_modules/.pnpm/@nuxt+devtools@1.0.8_nuxt@3.10.3_@parcel+watcher@2.4.0_@types+node@20.11.19_encoding@0.1.13_e_7xyykjgsd7axp37vwpgcmng5vu/node_modules/@nuxt/devtools/dist/runtime/plugins/devtools.server").default> &
  InjectionType<typeof import("../../node_modules/.pnpm/@nuxt+devtools@1.0.8_nuxt@3.10.3_@parcel+watcher@2.4.0_@types+node@20.11.19_encoding@0.1.13_e_7xyykjgsd7axp37vwpgcmng5vu/node_modules/@nuxt/devtools/dist/runtime/plugins/devtools.client").default> &
  InjectionType<typeof import("../../node_modules/.pnpm/@nuxt+ui@2.14.2_axios@1.6.8_nuxt@3.10.3_@parcel+watcher@2.4.0_@types+node@20.11.19_encoding@0_ruhzgbbomtjqjowrn45acxqjqe/node_modules/@nuxt/ui/dist/runtime/plugins/modals").default> &
  InjectionType<typeof import("../../node_modules/.pnpm/@nuxt+ui@2.14.2_axios@1.6.8_nuxt@3.10.3_@parcel+watcher@2.4.0_@types+node@20.11.19_encoding@0_ruhzgbbomtjqjowrn45acxqjqe/node_modules/@nuxt/ui/dist/runtime/plugins/colors").default> &
  InjectionType<typeof import("../../node_modules/.pnpm/@nuxtjs+color-mode@3.3.2_rollup@4.12.0/node_modules/@nuxtjs/color-mode/dist/runtime/plugin.server").default> &
  InjectionType<typeof import("../../node_modules/.pnpm/@nuxtjs+color-mode@3.3.2_rollup@4.12.0/node_modules/@nuxtjs/color-mode/dist/runtime/plugin.client").default> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.10.3_@parcel+watcher@2.4.0_@types+node@20.11.19_encoding@0.1.13_eslint@8.57.0_optionat_s7d46f3i2xvimlar2kzdzkszge/node_modules/nuxt/dist/app/plugins/chunk-reload.client").default> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.10.3_@parcel+watcher@2.4.0_@types+node@20.11.19_encoding@0.1.13_eslint@8.57.0_optionat_s7d46f3i2xvimlar2kzdzkszge/node_modules/nuxt/dist/app/plugins/check-if-layout-used").default> &
  InjectionType<typeof import("../../node_modules/.pnpm/@nuxt+ui-pro@1.0.2_axios@1.6.8_nuxt@3.10.3_@parcel+watcher@2.4.0_@types+node@20.11.19_encodin_iatrsbsja24ozpieearqoymouy/node_modules/@nuxt/ui-pro/plugins/presets").default> &
  InjectionType<typeof import("../../node_modules/.pnpm/@nuxt+ui-pro@1.0.2_axios@1.6.8_nuxt@3.10.3_@parcel+watcher@2.4.0_@types+node@20.11.19_encodin_iatrsbsja24ozpieearqoymouy/node_modules/@nuxt/ui-pro/plugins/scrollbars.client").default> &
  InjectionType<typeof import("../../node_modules/.pnpm/@nuxt+ui-pro@1.0.2_axios@1.6.8_nuxt@3.10.3_@parcel+watcher@2.4.0_@types+node@20.11.19_encodin_iatrsbsja24ozpieearqoymouy/node_modules/@nuxt/ui-pro/plugins/variables").default>

declare module '#app' {
  interface NuxtApp extends NuxtAppInjections { }

  interface NuxtAppLiterals {
    pluginName: 'nuxt:revive-payload:client' | 'nuxt:head' | 'nuxt:router' | 'nuxt:revive-payload:server' | 'nuxt:global-components' | 'nuxt:prefetch' | 'nuxt:checkIfPageUnused' | 'nuxt:chunk-reload' | 'nuxt:checkIfLayoutUsed'
  }
}

declare module 'vue' {
  interface ComponentCustomProperties extends NuxtAppInjections { }
}

export { }
