services:
  postgres:
    container_name: postgres
    image: postgres:13
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5433:5432

  redis:
    container_name: redis
    image: redis:6-alpine
    volumes:
      - redis_volume:/data
    ports:
      - 6379:6379

  adonis_app:
    container_name: adonis_app
    restart: always
    depends_on:
      - postgres
      - redis
    build:
      context: .
      target: dependencies
    ports:
      - 3333:3333
      - 9229:9229
    env_file:
      - .env
    environment:
      - PG_HOST=postgres
      - DB_CONNECTION=pg
      - REDIS_HOST=redis
      - REDIS_CONNECTION=local
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - ./:/home/node/app
    # Pour initialiser (lancer les seed) avant de lancer le serveur :
    # command: sh -c "dumb-init node ace migration:run && node ace db:seed && node ace serve --watch --node-args='--inspect=0.0.0.0'"
    # Une fois initialisé, toujours lancer le serveur avec :
    command: sh -c "dumb-init node ace migration:run && node ace serve --watch --node-args='--inspect=0.0.0.0'"

volumes:
  postgres_volume:
  redis_volume:
